### PR TITLE
Week1+week2+week3+week4

### PR DESCRIPTION
**Pull request by Sleepingisimportant**
Discord: Sleepingisimportant

API test:
http://52.70.76.242:3000/api/attraction/1
http://52.70.76.242:3000/api/attractions?page=1&keyword=%E5%8C%97%E6%8A%95

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Every attraction data should contain 1 or more image URLs.

**Comment by Sleepingisimportant** [comment]
Week1 + Week2 + Week3 
Discord: Sleepingisimportant

URLs to be tested:
http://52.70.76.242:3000/
http://52.70.76.242:3000/attraction/13
http://52.70.76.242:3000/api/attraction/1
http://52.70.76.242:3000/api/attractions?page=1
http://52.70.76.242:3000/api/attractions?page=1&keyword=%E5%8C%97%E6%8A%95

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
We don't use jQuery in our tasks.

**Comment by Sleepingisimportant** [comment]
Removed JQuery. Review re-requested. 

Discord: Sleepingisimportant

URLs to be tested:
http://52.70.76.242:3000/
http://52.70.76.242:3000/attraction/13
http://52.70.76.242:3000/api/attraction/1
http://52.70.76.242:3000/api/attractions?page=1
http://52.70.76.242:3000/api/attractions?page=1&keyword=%E5%8C%97%E6%8A%95

**Review by cwpeng — COMMENTED** [review]
Your website is broken, cannot connect to MySQL.

**Comment by Sleepingisimportant** [comment]
Could you please try again? Thanks!

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your code will load the same page multiple times if we scroll down to the bottom.
2. Your code will load pages of unfiltered attractions after we search for certain keyword.

**Comment by Sleepingisimportant** [comment]
Fixed: loading pages multiple times when scrolling the page. Currently, it will stop loading when the return value of nextpage is null.

Could you please give me an example of your second point? Could you provide the keywords you feed that led to the unexpected attractions shown?

**Review by cwpeng — COMMENTED** [review]
First issue is not resolved completely. Example for second issue below:
未命名-2

**Comment by Sleepingisimportant** [comment]
Changed the code according to the previous comments. Please review. Thank you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your APIs are broken again, try to find out the root cause and fix it. I think you do not use connection pool in a right way.

**Comment by Sleepingisimportant** [comment]
Tried fixing the connection pool. Review requested.

**Review by cwpeng — CHANGES_REQUESTED** [review]
You cannot change code of predefined page route: `@app.route("/attraction/<id>")`

Try to get attraction data through API, not template engine, for aligning with design of separation of front-end and backend.

**Comment by Sleepingisimportant** [comment]
**To be reviewed:**
1.  Get attraction data through API instead of template engine.
2. Submit: week 4 tasks.  Added Authentication functions & APIs(Login, Logout, verification)

**Discord:** Sleepingisimportant

**URLs to be tested:**
http://52.70.76.242:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
Aspect ratio of any images in your page should keep the same as original ones.

**Comment by Sleepingisimportant** [comment]
Fixed image aspect ration for both index.html and attraction.html.

**Comment by Sleepingisimportant** [comment]
Fixed the distorted aspect ratio of images in both index.html and attraction.html.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Circles in image slider should be on the top of image. Aspect ratio of image in attraction page is not stable in mobile version.
52 70 76 242_3000_attraction_1

**Comment by Sleepingisimportant** [comment]
[Request review]
Fixed instable aspect ratio of images in the slideshow under the screen width 600px.
Discord: Sleepingisimportant

URLs to be tested:
http://52.70.76.242:3000/attraction/1

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
